[functions]
  node_bundler = "esbuild"
  included_files = ["client_information/subscription_letter.JSON"]

[functions.environment]
  AWS_LAMBDA_NODEJS_VERSION = "18"

[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/pages/home_page/"
  status = 200